import { Link } from 'react-router-dom';

export default function Footer() {
  return (
    <footer className="lp-footer">
      <div className="lp-container lp-footer-inner">
        <div>
          <span className="lp-footer-logo">Smart API Builder</span>
          <p className="lp-footer-tagline">Generated. Not written.</p>
        </div>
        <nav className="lp-footer-links">
          <Link to="/app/smart-api">Launch App</Link>
          <a href="#features">Features</a>
          <a href="#how-it-works">How It Works</a>
        </nav>
      </div>
      <div className="lp-container">
        <p className="lp-footer-copy">
          Built for a hackathon submission. No AI calls at runtime — every artifact is generated by
          deterministic code.
        </p>
      </div>
    </footer>
  );
}
