import { Link } from 'react-router-dom';
import ProductPreview from './ProductPreview';
import UploadScreenMock from './UploadScreenMock';
import RevealOnScroll from './RevealOnScroll';

const TRUST_ITEMS = [
  { title: 'No Sign Up', sub: 'Use it instantly' },
  { title: 'Nothing Stored', sub: 'Processed in memory only' },
  { title: 'Developer First', sub: 'Built for speed' },
];

export default function Hero() {
  return (
    <section id="top" className="lp-section lp-hero">
      <div className="lp-container lp-hero-grid">
        <div>
          <RevealOnScroll>
            <span className="lp-pill">⚡ In-Memory · No Sign Up · Nothing Stored</span>
          </RevealOnScroll>

          <RevealOnScroll delay={0.1}>
            <h1 className="lp-heading-2xl lp-hero-headline">
              Build APIs.
              <br />
              <span className="lp-gradient-text">Instantly.</span>
            </h1>
          </RevealOnScroll>

          <RevealOnScroll delay={0.2}>
            <p className="lp-hero-sub">
              Upload a Postman collection. Get documentation, an SDK, types, an OpenAPI spec, cURL
              examples, React hooks, and a mock server back — in seconds. Every artifact is generated by
              deterministic code, not AI.
            </p>
          </RevealOnScroll>

          <RevealOnScroll delay={0.3}>
            <div className="lp-hero-ctas">
              <Link to="/app/smart-api" className="lp-btn lp-btn-primary">
                Launch Smart API →
              </Link>
              <a href="#how-it-works" className="lp-btn lp-btn-secondary">
                See how it works
              </a>
            </div>
          </RevealOnScroll>

          <RevealOnScroll delay={0.4}>
            <div className="lp-hero-trust">
              {TRUST_ITEMS.map((item) => (
                <div key={item.title} className="lp-hero-trust-item">
                  <strong>{item.title}</strong>
                  <span>{item.sub}</span>
                </div>
              ))}
            </div>
          </RevealOnScroll>
        </div>

        <RevealOnScroll delay={0.2} className="lp-hero-preview-col">
          <ProductPreview label="smartapi.dev/app/smart-api" float>
            <UploadScreenMock />
          </ProductPreview>
        </RevealOnScroll>
      </div>
    </section>
  );
}
