import { Router, Request, Response } from 'express';
import multer from 'multer';
import { parseCollection } from '../parser';
import { generateDocs } from '../generators/docs';
import { generateSDK } from '../generators/sdk';
import { generateCurlCommands } from '../generators/curl';
import { generateReactHooks } from '../generators/hooks';
import { generateTypes } from '../generators/typesGen';
import { generateOpenAPISpec } from '../generators/openapi';
import { generateMockServer } from '../generators/mock';
import { buildZip } from '../zip';

const upload = multer({ storage: multer.memoryStorage() });
const router = Router();

router.post('/generate', upload.single('collection'), async (req: Request, res: Response) => {
  if (!req.file) {
    return res.status(400).json({ error: 'No file uploaded. Field name must be "collection".' });
  }

  let collection: any;
  try {
    collection = JSON.parse(req.file.buffer.toString('utf-8'));
  } catch {
    return res.status(400).json({ error: 'Invalid JSON file' });
  }

  let endpoints;
  try {
    endpoints = parseCollection(collection);
  } catch (err: any) {
    return res.status(400).json({ error: err.message || 'Failed to parse collection' });
  }

  const collectionName = collection.info?.name || 'API';

  const docs = generateDocs(endpoints);
  const sdk = generateSDK(endpoints);
  const curl = generateCurlCommands(endpoints);
  const hooks = generateReactHooks(endpoints);
  const types = generateTypes(endpoints);
  const openapi = generateOpenAPISpec(endpoints, collectionName);
  const mockServer = generateMockServer(endpoints);

  const readme = [
    `# ${collectionName} - Generated Project`,
    '',
    'Generated by Smart API Builder.',
    '',
    '- docs/API.md - API documentation',
    '- sdk/api.ts - TypeScript SDK (axios)',
    '- curl/examples.md - cURL examples',
    '- hooks/hooks.ts - React Query hooks',
    '- types/models.ts - TypeScript interfaces',
    '- openapi.yaml - OpenAPI 3.0 spec',
    '- mock/server.ts - Express mock server (npm i express && npx ts-node mock/server.ts)',
    '',
  ].join('\n');

  const zipBuffer = await buildZip({
    'docs/API.md': docs,
    'sdk/api.ts': sdk,
    'curl/examples.md': curl,
    'hooks/hooks.ts': hooks,
    'types/models.ts': types,
    'openapi.yaml': openapi,
    'mock/server.ts': mockServer,
    'README.md': readme,
  });

  res.json({
    docs,
    sdk,
    curl,
    hooks,
    types,
    openapi,
    mockServer,
    zipBase64: zipBuffer.toString('base64'),
  });
});

export default router;
